#!/usr/bin/env zsh

sudo apk update

###############################################################################
# Install tmux
###############################################################################
sudo apk add tmux

if [ -d "/home/vscode/.tmux/plugins/tpm" ]
then
  echo "tmux plugin manager already installed."
else
  git clone https://github.com/tmux-plugins/tpm /home/vscode/.tmux/plugins/tpm
fi

sudo apk add xclip


###############################################################################
# zsh
###############################################################################
mkdir -p ~/.zsh

if [ -d "/home/vscode/.zsh/git-prompt.zsh" ]
then
  echo "zsh git-prompt plugin ager already installed"
else
  git clone --depth=1 https://github.com/woefe/git-prompt.zsh ~/.zsh/git-prompt.zsh
fi


###############################################################################
# nvim
###############################################################################
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# vim +'PlugInstall --sync' +qa
# nvim +'PlugInstall --sync' +qa


###############################################################################
# Misc
###############################################################################
sudo apk add ranger --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community


###############################################################################
# Link dotfiles
###############################################################################
cp -rsf /workspaces/.codespaces/.persistedshare/dotfiles/dotfiles/. /home/vscode/


