#!/usr/bin/env zsh

sudo apk update
sudo apk add tmux

cp -rsf /workspaces/.codespaces/.persistedshare/dotfiles/dotfiles/. /home/vscode/

# sudo apk add vim
# sudo apk add ranger

# sudo apk del ranger
# sudo apk add ranger --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community

##################################
# Codespaces Notes
##################################
# gh cs list
# gh cs delete
# gh cs create Comoto-Tech/dev-hub
# gh cs ssh
