#!/usr/bin/env zsh

sudo apk update

###############################################################################
# Install tmux
###############################################################################
sudo apk add tmux

if [ -d "/home/vscode/.tmux/plugins/tpm" ]
then
  echo "tmux plugin manager already installed."
else
  git clone https://github.com/tmux-plugins/tpm /home/vscode/.tmux/plugins/tpm
fi

sudo apk add xsel
sudo apk add xclip


###############################################################################
# Vim
###############################################################################
sudo apk add vim

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +'PlugInstall --sync' +qa


###############################################################################
# Misc
###############################################################################
sudo apk add ranger --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community


###############################################################################
# Link dotfiles
###############################################################################
cp -rsf /workspaces/.codespaces/.persistedshare/dotfiles/dotfiles/. /home/vscode/


##################################
# Codespaces Notes
##################################
# gh cs list
# gh cs delete
# gh cs create -R Comoto-Tech/dev-hub
# gh cs ssh
# gh cs logs
#
# tail -f /workspaces/.codespaces/.persistedshare/EnvironmentLog.txt
# cat /workspaces/.codespaces/.persistedshare/EnvironmentLog.txt
